[package]
name = "picmyweb2"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
regex = "1.0"
headless_chrome = "1.0.18"
tokio = { version = "1.0", features = ["full"] }
